events {}

http {
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://localhost:3000;

            # TODO: encaminhe Host.
            # TODO: encaminhe X-Real-IP.
            # TODO: encaminhe X-Forwarded-For.
            # TODO: encaminhe X-Forwarded-Proto.
        }
    }
}

