events {}

http {
    server {
        listen 8080;
        server_name localhost;

        # TODO: crie o proxy HTTP comum em /.

        # TODO: crie o location /socket.
        # TODO: configure versão HTTP e headers de upgrade.
        # TODO: encaminhe os headers de origem.
    }
}

