events {}

http {
    server {
        # TODO: escute a porta 8080.
        # TODO: defina localhost como server_name.

        # TODO: crie o location / e encaminhe para a aplicação da porta 3000.
    }
}

