events {}

http {
    server {
        listen 8080;
        server_name localhost;

        # TODO: crie o location para /usuarios/.
        # TODO: crie o location para /produtos/.
        # TODO: faça / responder "Gateway online" sem acessar outro serviço.
        # TODO: encaminhe os headers de proxy necessários.
    }
}

